name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          slug: MBurchard/bit-log
          token: ${{ secrets.CODECOV_TOKEN }}

#      - name: Upload coverage report
#        uses: actions/upload-artifact@v2
#        with:
#          name: coverage-report
#          path: coverage
#
#      - name: Upload coverage reports to Codecov
#        uses: codecov/codecov-action@v4.0.1
#        env:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          slug: MBurchard/bit-log
